# Generated by Django 5.0.7 on 2025-09-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsexshop', '0004_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('cantidad_devolver', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('producto_abierto', models.BooleanField()),
                ('empaque_original', models.BooleanField()),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True)),
                ('preferencia_resolucion', models.CharField(choices=[('Reemplazo', 'Reemplazo'), ('Reembolso', 'Reembolso')], max_length=10)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('acepta_terminos', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, to='appsexshop.usuario')),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('devolucion', models.ForeignKey(db_column='DevolucionId', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appsexshop.devolucion')),
                ('producto', models.ForeignKey(db_column='ProductoId    ', on_delete=django.db.models.deletion.CASCADE, to='appsexshop.producto')),
            ],
            options={
                'db_table': 'devoluciones_detalle',
            },
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoPedido', models.CharField(max_length=50, unique=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(default='pendiente', max_length=20)),
                ('UsuarioId', models.ForeignKey(db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appsexshop.usuario')),
            ],
            options={
                'db_table': 'historial_pedidos',
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='pedido',
            field=models.ForeignKey(db_column='HistorialPedidoId', on_delete=django.db.models.deletion.CASCADE, to='appsexshop.historialpedido'),
        ),
        migrations.CreateModel(
            name='HistorialPedidoDetalle',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField()),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HistorialId', models.ForeignKey(db_column='HistorialId', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appsexshop.historialpedido')),
                ('ProductoId', models.ForeignKey(db_column='ProductoId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appsexshop.producto')),
            ],
            options={
                'db_table': 'historial_pedidos_detalle',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='appsexshop.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
